snacks_test/Member/urls.py
from django.urls import path

from Member import views

app_name = 'Member'
urlpatterns = [
    path('', views.index, name='index'),
    # 注册
    path('register/', views.register, name='register'),
    # 获取验证码
    # path('code/', views.generate_code, name='generate_code'),
    # 登录
    path('login/', views.login, name='login'),
    # 退出
    path('logout/', views.logout, name='logout'),
    # 修改密码
    path('password/', views.password, name='password'),
    # 找回密码
    path('getpassword/', views.getpassword, name='getpassword'),
    # 我的订单
    path('list/', views.order_list, name='order_list'),
    # 历史订单
    path('old_list/', views.old_list, name='old_list'),
    # 我的收藏
    path('collection/', views.collection, name='collection'),
    # 个人信息
    path('profile/', views.profile, name='profile'),
    # 收货地址
    path('address/', views.address, name='address'),
    # 编辑收货地址
    path('address_write/', views.address_write, name='address_write'),
    # 查询订单
    path('dingdan/', views.dingdan, name='dingdan'),
]

snacks_test/Tmp/urls.py
from django.urls import path, include, re_path

from Tmp import views

app_name = 'Tmp'
urlpatterns = [
    path('base/',views.base,name='base'),
    path('',views.index, name='index'),
    # path('index/',views.index, name='index'),
    path('cuxiao/',views.cuxiao, name='cuxiao'),
    path('news/',views.news, name='news'),
    path('lingshi/<int:cid>/',views.lingshi, name='lingshi'),
    path('lingshibase/',views.lingshi_base, name='lingshibase'),
    path('test/',views.test,name='test'),
    path('ditu/',views.ditu,name='ditu'),
    path('cart/<int:cid>/',views.addcart,name='cart'),
    path('buynow/<int:cid>/',views.buynow,name='buynow'),
    path('confirm/<int:gid>/<int:bid>/',views.confirm,name='confirm'),
    path('zhifu/<int:gid>/<int:bid>/<int:cid>/',views.zhifu,name='zhifu'),
    path('doulei/',views.doulei,name='doulei'),
    path('guazi/',views.guazi,name='guazi'),
    path('haitai/',views.haitai,name='haitai'),
    path('jianguo/',views.jianguo,name='jianguo'),
    path('yu/',views.yu,name='yu'),
    path('done/',views.done,name='done'),
    path('pay/',views.ali_buy,name='pay'),
    path('search/', views.search, name='search')





]

snacks_test/snacks_test/urls.py
from django.contrib import admin
from django.urls import path, include

from Tmp import views

urlpatterns = [
    # path('App/', App.site.urls),
    # path('', views.index),
    path('tmp/', include('Tmp.urls',namespace='tmp')),

    # path('app/', include('App.urls', namespace='app')),
    path('member/', include('Member.urls', namespace='member')),
    path('admin/', include('lingshi_admin.urls', namespace='admin'))
]

snacks_test/Member/models.py
from django.db import models


# Create your models here.

snacks_test/Member/views.py
import hashlib
from random import randint

from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.template import context
from django.urls import reverse

from Tmp.models import User, Order_Commodity, Order, Address
from Member.forms import UserForm, ChangeForm, GetForm
from Member.yanzheng import send_sms
from snacks_test import settings


def index(request):
    return render(request, 'Member/user_index.html', {'username': request.session.get('username')})
    # return render(request, 'base.html')


# # 获取验证码
# def generate_code(request):
#     username = request.POST.get('username')
#     password = request.POST.get('password')
#     confirm_password = request.POST.get('confirm_password')
#     verification = randint(100000, 999999)
#     request.session['verification'] = verification
#     request.session['username'] = username
#     request.session['password'] = password
#     request.session['confirm_password'] = confirm_password
#     send_mail('验证信息', '您的验证码为{},请您及时注册'.format(verification), settings.EMAIL_FROM, ['2567317859@qq.com'])
#     return render(request, 'Member/register.html', **locals())


# 注册
def register(request):
    form = UserForm()
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        user = User()
        form = UserForm(request.POST)
        if form.is_valid():
            print(request.session.get('verification23342'))
            if not request.POST.get('yzm'):
                verification = randint(10000, 999999)
                request.session['verification'] = verification
                if username.isdigit():
                    send_sms(username, {'number': verification})
                else:
                    send_mail('验证信息', '您的验证码为{},请您及时注册'.format(verification), settings.EMAIL_FROM,
                              [username])
                return render(request, 'Member/register.html', context={
                    'form': form,
                    'username': username,
                    'password': password,
                    'confirm_password': confirm_password,
                })
            elif int(request.POST.get('yzm')) != request.session.get('verification'):
                print(request.POST.get('yzm'), type(request.POST.get('yzm')))
                print(request.session.get('verification'), type(request.session.get('verification')))
                return render(request, 'Member/register.html', {'msg': '您输入的验证码有误，请重新注册'})
            else:
                print(username, password)
                password = hashlib.sha1(password.encode('utf8')).hexdigest()
                user.password_hash = password
                if username.isdigit():
                    user.telephone = username
                    user.registration_number = username
                else:
                    user.email = username
                    user.registration_number = username
                user.save()
                return render(request, 'App/product/index.html')
        return render(request, 'Member/register.html', {'form': form})
    return render(request, 'Member/register.html', {'form': form})


# 修改密码
def password(request):
    form = ChangeForm()
    if request.method == 'POST':
        form = ChangeForm(request.POST)
        if form.is_valid():
            old_value = request.session.get('username')
            old_password = hashlib.sha1(request.POST.get('old_password').encode('utf8')).hexdigest()
            new_password = hashlib.sha1(request.POST.get('new_password').encode('utf8')).hexdigest()
            if old_value.isdigit():
                res = User.objects.filter(telephone__contains=old_value).first()
            else:
                res = User.objects.filter(email__contains=old_value).first()
            if res.password_hash != old_password:
                return render(request, 'Member/change_password.html', {'msg': '您输入的原密码有误'})
            elif old_password == new_password:
                return render(request, 'Member/change_password.html', {'msg1': '您输入的新密码与旧密码一致'})
            res.password_hash = new_password
            res.save()
            return redirect(reverse('member:logout'))
        return render(request, 'Member/change_password.html', {'username': request.session.get('username'), 'form': form})
    return render(request, 'Member/change_password.html', {'username': request.session.get('username'), 'form': form})


# 登录
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        password = hashlib.sha1(password.encode('utf8')).hexdigest()
        print(username, password)
        if username.isdigit():
            res = User.objects.filter(telephone__contains=username, password_hash__contains=password)
        else:
            res = User.objects.filter(email__contains=username, password_hash__contains=password)
        if len(res) > 0:
            request.session['username'] = username
            return redirect(reverse('tmp:index'))
        return redirect(reverse('member:login'))
    return render(request, 'Member/login.html')


# 退出
def logout(request):
    response = redirect(reverse('tmp:index'))
    request.session.flush()
    return response


# 找回密码
def getpassword(request):
    form = GetForm()
    if request.method == 'POST':
        form = GetForm(request.POST)
        if form.is_valid():
            newpassword = hashlib.sha1(b'a123').hexdigest()
            username = request.POST.get('username')
            email = request.POST.get('email')
            if username.isdigit():
                user = User.objects.filter(telephone__contains=username).first()
            else:
                user = User.objects.filter(email__contains=username).first()
            user.password_hash = newpassword
            user.save()
            send_mail('找回密码', '您的密码已重置，新密码为{}'.format('a123'), settings.EMAIL_FROM, [email])
            return render(request, 'base.html')
    return render(request, 'Member/getpassword.html', {'form': form})


# 我的订单
def order_list(request):
    username = request.session.get('username')
    if username.isdigit():
        user = User.objects.filter(telephone__contains=username).first()
    else:
        user = User.objects.filter(email__contains=username).first()
    order = Order.objects.filter(uid=user.id).all()
    print(order, 'ceshishuju')
    if len(order) == 0:
        print(order, '测试数据')

        return render(request, 'Member/order_list.html', {'username': username, 'order': order})
    else:
        print(order[0])
        order_commoditys = []
        for i in range(0, len(order)):
            order_commodity = Order_Commodity.objects.filter(oid=order[i].id).all()
            for j in range(0, len(order_commodity)):
                print(order_commodity)
                order_commodity1 = order_commodity[j]
                order_commoditys.append(order_commodity1)
                queryset = Order_Commodity.objects.filter(pk__in=[x.pk for x in order_commoditys])
                if j == len(order_commodity) - 1:
                    if i == len(order) - 1:
                        return render(request, 'Member/order_list.html', {
                            'username': username,
                            'order': order,
                            'order_commodity': queryset,
                        })


# 历史订单
def old_list(request):
    username = request.session.get('username')
    if username.isdigit():
        user = User.objects.filter(telephone__contains=username).first()
    else:
        user = User.objects.filter(email__contains=username).first()
    order = Order.objects.filter(uid=user.id).all()
    if len(order) == 0:
        return render(request, 'Member/order_oldlist.html', {'username': username, 'order': order})
    else:
        order_commoditys = []
        for i in range(0, len(order)):
            order_commodity = Order_Commodity.objects.filter(oid=order[i].id).all()
            for j in range(0, len(order_commodity)):
                print(order_commodity)
                order_commodity1 = order_commodity[j]
                order_commoditys.append(order_commodity1)
                queryset = Order_Commodity.objects.filter(pk__in=[x.pk for x in order_commoditys])
                if j == len(order_commodity) - 1:
                    if i == len(order) - 1:
                        return render(request, 'Member/order_oldlist.html', {
                            'username': username,
                            'order': order,
                            'order_commodity': queryset,
                        })


# 我的收藏
def collection(request):
    return render(request, 'Member/collection_list.html', {'username': request.session.get('username')})


# 个人信息
def profile(request):
    return render(request, 'Member/profile.html', {'username': request.session.get('username')})


# 收货信息
def address(request):
    username = request.session.get('username')
    if username.isdigit():
        res = User.objects.filter(telephone__contains=username).first()
    else:
        res = User.objects.filter(email__contains=username).first()
    my_address = Address.objects.filter(uid=res.id).all()
    return render(request, 'Member/address_list.html', {'username': username,
                                                        'my_address': my_address,
                                                        })


# 填写订单
def address_write(request):
    username = request.session.get('username')
    if request.method == 'POST':
        if username.isdigit():
            res = User.objects.filter(telephone__contains=username).first()
        else:
            res = User.objects.filter(email__contains=username).first()

snacks_test/templates/Member/address_list.html
{% extends 'Member/base.html' %}
{% load static %}
{% block loginsideright %}
    <div id="loginsideright" style="margin-bottom:20px;">


        <div class="address_title">收货人信息</div>
        <div class="mt15" style=" text-align:right;">您已添加1个收货地址, 最多可添加10个<a href="{% url 'member:address_write' %}"
                                                                            class="new_address_btn ml10"
                                                                            >新增收货地址</a></div>

        <script type="text/javascript" src="http://www.lingshi.com/js/utils.js"></script>
        <script type="text/javascript" src="http://www.lingshi.com/js/region.js"></script>
        <script type="text/javascript" src="http://www.lingshi.com/js/shopping.js"></script>
        <script type="text/javascript">
            region.isAdmin = false;
            var consignee_not_null = "收货人姓名不能为空！";
            var country_not_null = "国家";
            var province_not_null = "省份";
            var city_not_null = "城市";
            var district_not_null = "区域";
            var invalid_email = "您输入的邮件地址不是一个合法的邮件地址。";
            var address_not_null = "收货人的详细地址不能为空！";
            var tele_not_null = "电话不能为空！";
            var shipping_not_null = "请您选择配送方式！";
            var payment_not_null = "请您选择支付方式！";
            var goodsattr_style = "1";
            var tele_invaild = "电话号码不是有效的号码！";
            var zip_not_num = "邮政编码只能填写数字";
            var mobile_invaild = "手机号码不是合法号码！";

            function add_new_address() {
                var consignee_length = 1;
                if (consignee_length >= 10) {
                    alert('您的收货地址已达上限！');
                } else {
                    showbox('http://member.lingshi.com/?act=address_list', 'http://pay.lingshi.com/?step=consignee&address_id=0', 855, 380);
                }
            }
        </script>
        {% for address in my_address %}
        <table border="0" cellpadding="0" cellspacing="0" class="table_address mt15" style="width: 80%">
            <tbody>

            <tr>
                <td colspan="2" class="cole54347 font14">收货地址</td>
                {% if address.isdefault == 1 %}
                <td width="24%" align="right"><a class="default_address mr10">默认常用地址</a><a href="javascript:void(0)"
                                                                                           onclick="showbox('http://member.lingshi.com/?act=address_list','http://pay.lingshi.com/?step=consignee&amp;address_id=272266',855,380)"
                                                                                           class="col09c">修改</a></td>
            {% endif %}
            </tr>
            <tr>
                <td width="11%" align="right" class="col999">收货人:</td>
                <td width="65%">{{ address.receive }}</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td align="right" class="col999">收货地址:</td>
                <td>{{ address.address }}</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td align="right" class="col999">手机号码:</td>
                <td>{{ address.telephone }}</td>
                <td>&nbsp;</td>
            </tr>
            </tbody>
        </table>
        {% endfor %}


    </div>
{#    <body>#}
{#    <form action="http://pay.lingshi.com/" method="post" name="theForm" id="theForm"#}
{#          onsubmit="return checkConsignee(this);">#}
{#        <div class="table_info">#}
{##}
{#            <div class="add_addr_info">#}
{#                <span>使用新的收货地址</span>#}
{#            </div>#}
{#            <table width="100" class="table_address" border="0" cellspacing="0" cellpadding="0">#}
{#                <tbody>#}
{#                <tr>#}
{#                    <td width="116"><em class="sign">*</em>收货人：</td>#}
{#                    <td colspan="3">#}
{#                        <input name="consignee" type="text" class="input_01" value="">#}
{#                        <span class="notice" id="consignee_notice"></span>#}
{#                    </td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td width='50px'><em class="sign">*</em>配送区域:</td>#}
{#                    <td colspan="3">#}
{#                        <select name="country" class="select" id="selCountries"#}
{#                                onchange="region.changed(this, 1, 'selProvinces')" >#}
{#                            <option value="0" >请选择国家</option>#}
{#                            <option value="1" selected="">中国</option>#}
{#                            <option value="3479">美国</option>#}
{#                            <option value="3485">日本</option>#}
{#                            <option value="3494">加拿大</option>#}
{#                        </select>#}
{#                        <select name="province" id="selProvinces" onchange="region.changed(this, 2, 'selCities')"#}
{#                                class="select">#}
{#                            <option value="0">请选择省</option>#}
{#                            <option value="2">北京</option>#}
{#                            <option value="3">安徽</option>#}
{#                            <option value="4">福建</option>#}
{#                            <option value="5">甘肃</option>#}
{#                            <option value="6">广东</option>#}
{#                            <option value="7">广西</option>#}
{#                            <option value="8">贵州</option>#}
{#                            <option value="9">海南</option>#}
{#                            <option value="10">河北</option>#}
{#                            <option value="11">河南</option>#}
{#                            <option value="12">黑龙江</option>#}
{#                            <option value="13">湖北</option>#}
{#                            <option value="14">湖南</option>#}
{#                            <option value="15">吉林</option>#}
{#                            <option value="16">江苏</option>#}
{#                            <option value="17">江西</option>#}
{#                            <option value="18">辽宁</option>#}
{#                            <option value="19">内蒙古</option>#}
{#                            <option value="20">宁夏</option>#}
{#                            <option value="21">青海</option>#}
{#                            <option value="22">山东</option>#}
{#                            <option value="23">山西</option>#}
{#                            <option value="24">陕西</option>#}
{#                            <option value="25">上海</option>#}
{#                            <option value="26">四川</option>#}
{#                            <option value="27">天津</option>#}
{#                            <option value="28">西藏</option>#}
{#                            <option value="29">新疆</option>#}
{#                            <option value="30">云南</option>#}
{#                            <option value="31">浙江</option>#}
{#                            <option value="32">重庆</option>#}
{#                            <option value="33">香港</option>#}
{#                            <option value="34">澳门</option>#}
{#                            <option value="35">台湾</option>#}
{#                        </select>#}
{#                        <select name="city" id="selCities" onchange="region.changed(this, 3, 'selDistricts')"#}
{#                                class="select">#}
{#                            <option value="0">请选择市</option>#}
{#                        </select>#}
{##}
{#                        <select name="district" id="selDistricts" style="display:none;" class="select">#}
{#                            <option value="0">请选择区</option>#}
{#                        </select>#}
{#                        <span class="notice" id="region_notice"></span>#}
{#                    </td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><em class="sign">*</em>详细地址：</td>#}
{#                    <td colspan="3">#}
{#                        <input name="address" type="text" class="input_02" value="">#}
{#                        <span class="notice" id="address_notice"></span>#}
{#                    </td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><em class="sign">*</em>手机号码：</td>#}
{#                    <td width="190">#}
{#                        <input name="mobile" type="text" class="input_01" value="">#}
{#                    </td>#}
{#                    <td width="97"><em class="color999">或</em>&nbsp;&nbsp;&nbsp;&nbsp;固定电话：</td>#}
{#                    <td width="497">#}
{#                        <input name="tel" type="text" class="input_01" value="">#}
{#                        <span class="notice" id="mobile_notice"></span>#}
{#                    </td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><em class="sign">&nbsp;&nbsp;</em>邮箱：</td>#}
{#                    <td>#}
{#                        <input name="email" type="text" class="input_01" value="">#}
{#                    </td>#}
{#                    <td colspan="2">#}
{#                        <span class="" style="color:#999;">用来接收订单提醒邮件，便于您及时了解订单</span>#}
{#                        <span class="notice" id="email_notice"></span>#}
{#                    </td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td></td>#}
{#                    <td colspan="3" style="padding-bottom:15px;">#}
{#                        <input type="hidden" name="step" value="consignee">#}
{#                        <input type="hidden" name="act" value="confirm">#}
{#                        <input type="hidden" name="logintype" value="ajax">#}
{#                        <input type="hidden" name="back_act" value="http://member.lingshi.com/?act=address_list">#}
{#                        <input name="address_id" type="hidden" value="0">#}
{##}
{#                        <input type="submit" class="btn_save" value="保存收货人信息">#}
{#                        <input type="checkbox" class="check" value="1" name="default" id="checkbox">#}
{#                        <label for="checkbox">保存为默认收货地址</label></td>#}
{#                </tr>#}
{#                </tbody>#}
{#            </table>#}
{#        </div>#}
{#    </form>#}
{#    <script type="text/javascript">#}
{#        var process_request = "正在处理您的请求...";#}
{#        var username_empty = "- 用户名不能为空。";#}
{#        var username_shorter = "- 长度不能少于3个字符";#}
{#        var username_invalid = "- 用户名只能是由字母数字以及下划线组成。";#}
{#        var password_empty = "- 登录密码不能为空。";#}
{#        var password_shorter = "- 密码不能少于6个字符";#}
{#        var confirm_password_invalid = "- 两次输入密码不一致";#}
{#        var email_empty = "- Email为空";#}
{#        var email_invalid = "- Email不是合法的地址";#}
{#        var agreement = "- 您没有接受协议";#}
{#        var msn_invalid = "- msn地址不是一个有效的邮件地址";#}
{#        var qq_invalid = "- QQ号码不是一个有效的号码";#}
{#        var home_phone_invalid = "- 家庭电话不是一个有效号码";#}
{#        var office_phone_invalid = "- 办公电话不是一个有效号码";#}
{#        var mobile_phone_invalid = "- 手机号码不是一个有效号码";#}
{#        var msg_un_blank = "- 用户名不能为空";#}
{#        var msg_un_length = "* 用户名最长不得超过7个汉字";#}
{#        var msg_un_format = "* 用户名含有非法字符";#}
{#        var msg_un_registered = "* 用户名已经存在,请重新输入";#}
{#        var msg_can_rg = "* 可以注册";#}
{#        var msg_email_blank = "* 邮件地址不能为空";#}
{#        var msg_email_registered = "* 邮箱已存在,请重新输入";#}
{#        var msg_email_format = "* 邮件地址不合法";#}
{#        var msg_blank = "不能为空";#}
{#        var no_select_question = "- 您没有完成密码提示问题的操作";#}
{#        var passwd_balnk = "- 密码中不能包含空格";#}
{#        var invite_invalid = "- 邀请人不存在";#}
{#        var username_exist = "用户名 %s 已经存在";#}
{#        var compare_no_goods = "您没有选定任何需要比较的商品或者比较的商品数少于 2 个。";#}
{#        var btn_buy = "购买";#}
{#        var is_cancel = "取消";#}
{#        var select_spe = "请选择商品属性";#}
{#    </script>#}
{#    </body>#}
{% endblock loginsideright %}

snacks_test/templates/Member/base.html
{% extends 'base.html' %}
{% load static %}
    {% block scripts %}
    <link href="{% static 'Member/css/menu.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'Member/css/common.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'Member/css/customer.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'Member/css/tab.css' %}" rel="stylesheet" type="text/css">
    {% endblock scripts %}
    {% block script %}
    {% endblock script %}
    {% block styles %}
    {% endblock styles %}
{% block body %}
    <div id="main">

    <div class="block box">
        <div id="ur_here">
            当前位置: <a href="http://www.lingshi.com/" title="中国零食网">首页</a> <code>&gt;</code> 用户中心
        </div>
    </div>

    <div class="blank"></div>
    <div id="logincontent">

        <div class="loginsideleft">
            <div><a href="http://member.lingshi.com/" class="my_account">我的零食网</a></div>
            <div class="userMenu mt10">
                <h5 class="btn-slide">订单中心</h5>
                <ul class="panel">
                    <li><a href="{% url 'member:order_list' %}">我的订单</a></li>
                    <!-- <li><a href="http://mall.lingshi.com/index.php?app=buyer_order" target="_blank">商城订单</a></li> -->
                    <li><a href="{% url 'member:old_list' %}">历史订单</a></li>
                    <li><a href="{% url 'member:collection' %}">我的收藏</a></li>
                    <li><a href="#">我的评论</a></li>
                </ul>
                <h5 class="btn-slide">账户中心</h5>
                <ul class="panel">
                    <li><a href="{% url 'member:profile' %}">个人信息</a></li>
                    <li><a href="#">我的积分</a>
                    </li>
                    <li><a href="#">我的代金券</a>
                    </li>
                    <li><a href="#">账户余额</a>
                    </li>
                    <li><a href="#">礼品卡充值</a>
                        <!-- <li><a href="http://member.lingshi.com/?act=bind_member_card" >绑定会员卡</a></li> -->
                    </li>
                    <li><a href="{% url 'member:address' %}">收货信息</a></li>

                    <li><a href="{% url 'member:password' %}">修改密码</a></li>
                </ul>
                <h5 class="btn-slide">服务中心</h5>
                <ul class="panel">
                    <li><a href="{% url 'member:dingdan' %}">订单速查</a></li>
                    <!-- <li><a href="http://member.lingshi.com/?act=return_order" >退换货申请</a></li> -->
                    <!-- <li><a href="http://member.lingshi.com/?act=my_order_return" >退换货记录</a></li> -->
                    <!-- <li><a href="http://www.lingshi.com/user_email.php?act=user_email" >订阅优惠信息</a></li> -->
                    <li><a href="#">会员留言</a></li>
                    <li><a href="#">我要投诉</a></li>
                    <!-- <li><a href="http://member.lingshi.com/?act=vote_inline" >网络调查</a></li> -->
                    <!--<li><a href="http://www.lingshi.com/customer.php?act=booking_list">缺货登记</a></li>-->
                </ul>
            </div>
            <script type="text/javascript">
                $(document).ready(function () {
                    $(".btn-slide").click(function () {
                        $(this).next(".panel").slideToggle("fast");
                        $(this).toggleClass("active");
                    });
                });
            </script>
        </div>
        {% block loginsideright %}

        {% endblock loginsideright %}
    </div>
    <div class="blank"></div>
</div>
<br>
<div class="clear"></div>
{% endblock body %}

snacks_test/templates/Member/change_password.html
{% extends 'Member/base.html' %}
{% load static %}
{% block style %}
    <style>
        table {
            width: 100%;
        }

        span {
            color: red;
        }
    </style>
{% endblock style %}
{% block loginsideright %}
    <div id="loginsideright" style="margin-bottom:20px;">


        <script type="text/javascript" src="{% static 'Member/js/utils.js' %}"></script>
        <script type="text/javascript">
            var bonus_sn_empty = "请输入您要添加的代金券序列号！";
            var bonus_sn_error = "您输入的代金券序列号格式不正确！";
            var email_empty = "请输入您的电子邮件地址！";
            var email_error = "您输入的电子邮件地址格式不正确！";
            var old_password_empty = "请输入您的原密码！";
            var new_password_empty = "请输入您的新密码！";
            var confirm_password_empty = "请输入您的确认密码！";
            var both_password_error = "您现两次输入的密码不一致！";
            var msg_blank = "不能为空";
            var no_select_question = "- 您没有完成密码提示问题的操作";
        </script>
        <h5><span>修改密码</span></h5>
        <div class="blank"></div>
        <form name="formPassword" action="{% url 'member:password' %}" method="post">
            {% csrf_token %}
            <table border="0" cellpadding="5" cellspacing="1" bgcolor="#dddddd" class="table1" style="width: 100%;">
                <tbody>
                <tr>
                    <td width="28%" align="right" bgcolor="#FFFFFF">输入原密码：</td>
                    <td width="76%" align="left" bgcolor="#FFFFFF"><input name="old_password" type="password" size="25" class="inputBg">
                        <span>
                            {% for error in form.old_password.errors %}
                                {{ error }}
                            {% endfor %}
                            {{ msg }}
                        </span>
                    </td>
                </tr>
                <tr>
                    <td width="28%" align="right" bgcolor="#FFFFFF">新密码：</td>
                    <td align="left" bgcolor="#FFFFFF"><input name="new_password" type="password" size="25" class="inputBg">
                        <span>
                            {% for error in form.new_password.errors %}
                                {{ error }}
                            {% endfor %}
                            {{ msg1 }}
                        </span>
                    </td>
                </tr>
                <tr>
                    <td width="28%" align="right" bgcolor="#FFFFFF">确认密码：</td>
                    <td align="left" bgcolor="#FFFFFF"><input name="confirm_password" type="password" size="25" class="inputBg">
                        <span>
                            {% for error in form.confirm_password.errors %}
                                {{ error }}
                            {% endfor %}
                        </span>
                    </td>
                </tr>

                <input type="hidden" name="change_password" value="15941265505">


                <tr>
                    <td colspan="2" align="center" bgcolor="#FFFFFF"><input name="act" type="hidden"
                                                                            value="act_edit_password">
                        <input name="submit" type="submit" class="bnt_blue_1" value="确认修改">
                    </td>
                </tr>
                </tbody>
            </table>
        </form>


    </div>
{% endblock loginsideright %}